// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiAcmeEncuestasV1;

#nullable disable

namespace WebApiAcmeEncuestasV1.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiAcmeEncuestasV1.Models.CamposEncuesta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<string>("nombreCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("requerido")
                        .HasColumnType("bit");

                    b.Property<string>("tipoCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tituloCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("EncuestaId");

                    b.ToTable("Campos");
                });

            modelBuilder.Entity("WebApiAcmeEncuestasV1.Models.Encuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("descripcionEncuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEncuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Encuesta");
                });

            modelBuilder.Entity("WebApiAcmeEncuestasV1.Models.LlenarEncuesta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Datos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCampo")
                        .HasColumnType("int");

                    b.Property<int>("NoLlenado")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Llenarencuesta");
                });

            modelBuilder.Entity("WebApiAcmeEncuestasV1.Models.CamposEncuesta", b =>
                {
                    b.HasOne("WebApiAcmeEncuestasV1.Models.Encuesta", null)
                        .WithMany("Campos")
                        .HasForeignKey("EncuestaId");
                });

            modelBuilder.Entity("WebApiAcmeEncuestasV1.Models.Encuesta", b =>
                {
                    b.Navigation("Campos");
                });
#pragma warning restore 612, 618
        }
    }
}
